# Generated by Django 5.2 on 2025-05-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
    ]

    operations = [
    ]
